Handling github events
aosus/Torjoman pull request #17
Opened 2022-10-03 10:51 UTC by TheKaram

- make_pull_request function now works fine, solvers #14 
- Handle Pull Request events
- Handle Pull request comments, still needs some work
- Many other improvements and fixes

2022-10-13 19:08 UTC, TheAwiteb requested changes

2022-10-13 19:08 UTC, TheAwiteb commented on translation/models.py
> +        ]
اظن تقدر تستخدم `self.sourcetranslation_set.objects.values_list("translation")` افضل

2022-10-13 19:08 UTC, TheAwiteb commented on translation/models.py
> +        ]
اظن تقدر تستخدم `self.usertranslation_set.objects.values_list("translation")` افضل

2022-10-13 19:08 UTC, TheAwiteb commented on translation/models.py
> +            return
تقدر تسند وتقارن في نفس السطر
```python
if (translation := translation.strip()) == "":
    return
```

2022-10-13 19:08 UTC, TheAwiteb commented on translators/api.py
> +    if payload.platform not in list(platforms.keys()):
شيل `list` ال `in` اهم شي يكون `iterable` مايهم التايب

2022-10-13 19:08 UTC, TheAwiteb commented on translators/api.py
> +    )
اشوف لو يكون فيه ميثود في `TranslatorRegister` تسوي المُترجِم افضل

2022-10-13 19:08 UTC, TheAwiteb commented on translators/api.py
> +    if payload.platform not in list(platforms.keys()):
شيل `list` ال `in` اهم شي يكون `iterable` مايهم التايب

2022-10-13 19:08 UTC, TheAwiteb commented on translators/models.py
> +        return [platform.name for platform in self.platform_set.all()]
اظن تقدر تستخدم `self.platform_set.objects.values_list("name")` افضل

2022-10-13 19:08 UTC, TheAwiteb commented on translators/models.py
> +        return {f"{platform.name}": platform for platform in Platform.objects.all()}
```python
return {platform.name: platform for platform in Platform.objects.all()}
```

2022-10-13 19:08 UTC, TheAwiteb commented on translators/api.py
> +    if payload.platform not in list(platforms.keys()):
اظن كمان مايحتاج `platforms.keys` يكفي `platforms`

2022-10-14 08:09 UTC, TheKaram commented on translators/api.py
> +    )
كيف يعني؟ ممكن توضيح؟

2022-10-14 08:14 UTC, TheAwiteb commented on translators/api.py
> +    )
مثلآ ميثود اسمها `to_translator` في `TranslatorRegister` -الي هو تايب ال payload- ترجعلك `Translator` بنفس الطريقة الي سويت فيها الاوبجكت هنا

2022-10-14 08:16 UTC, TheAwiteb commented on translators/api.py
> +    )
او classmethod في `Translator` يكون اسمها `from_register` تستقبل ال payload

2022-10-14 08:51 UTC, TheAwiteb approved these changes

2022-10-14 08:53 UTC, TheAwiteb commented
يعطيك العافية عمل تشكر عليه @TheKaram 👏🏻👏🏻

2022-10-14 08:58 UTC, TheKaram commented
الله يعافيك @TheAwiteb

2022-10-14 13:48 UTC, merged